### ISSUE TITLE
Suggestion for SEE ALSO

### ISSUE THREAD

**Issue by cpansprout** [benkasminbullock/Unicode-Diacritic-Strip#4]
You could also mention Text::Unaccent and Text::Unaccent::PurePerl.

**Comment by benkasminbullock** [comment]
I don't mind mentioning them, although Text::Unaccent looks like it is abandoned and predates the current Perl Unicode encoding.

**Comment by benkasminbullock** [comment]
Spoke too soon, I have just tried it and it looks like it still works.

**Comment by benkasminbullock** [comment]
This was included in version 0.20 so this bug should be closed.
